// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HUMG.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("HUMG.Models.H38", b =>
                {
                    b.Property<string>("H38ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("H38Name")
                        .HasColumnType("TEXT");

                    b.HasKey("H38ID");

                    b.ToTable("H38");
                });
#pragma warning restore 612, 618
        }
    }
}
